name: KD
favicon: null
layout_spectrum: 0.13287499826401472
typography_spectrum: 0.15034862281754613
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.28846970084123313
  lightness: 0.2068498234730214
  saturation: 0.8165866937488317
  rhythmicContrast: 0.31613534572534263
purpose: []
