name: KD
favicon: null
layout_spectrum: 0.13287499826401472
typography_spectrum: 0.15034862281754613
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171711'
    - '#fafefd'
    - '#fdc83f'
    - '#a97d39'
    - '#555828'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 1
purpose: []
